2020-12-03 22:49:52,015 INFO    MainThread:10320 [wandb_setup.py:_flush():70] setting env: {}
2020-12-03 22:49:52,015 INFO    MainThread:10320 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2020-12-03 22:49:52,016 INFO    MainThread:10320 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-03 22:49:52,016 INFO    MainThread:10320 [wandb_init.py:_log_setup():303] Logging user logs to D:\pangqian\python\tidalDetect\Tidal\wandb\run-20201203_224951-3pzpv1oc\logs\debug.log
2020-12-03 22:49:52,016 INFO    MainThread:10320 [wandb_init.py:_log_setup():304] Logging internal logs to D:\pangqian\python\tidalDetect\Tidal\wandb\run-20201203_224951-3pzpv1oc\logs\debug-internal.log
2020-12-03 22:49:54,902 INFO    MainThread:10320 [wandb_run.py:_console_start():1218] atexit reg
2020-12-03 22:49:54,903 INFO    MainThread:10320 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-12-03 22:49:54,904 INFO    MainThread:10320 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-12-03 22:49:54,904 INFO    MainThread:10320 [wandb_run.py:_redirect():1132] Redirects installed.
2020-12-03 22:50:06,933 INFO    MainThread:10320 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 1
2020-12-03 22:50:06,933 INFO    MainThread:10320 [wandb_run.py:_restore():1160] restore
2020-12-03 22:50:06,937 INFO    MainThread:10320 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "1bdec641a8c14a0eb491201a8891ffc9"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 811
      total_bytes: 811
    }
  }
}

2020-12-03 22:50:08,963 INFO    MainThread:10320 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "e06293349147414b9eff15eba023bd27"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 6653
      total_bytes: 6653
    }
  }
}

2020-12-03 22:50:10,094 INFO    MainThread:10320 [wandb_run.py:_show_files():1517] logging synced files
2020-12-03 22:50:10,094 INFO    MainThread:10320 [internal.py:handle_exit():138] Internal process exited
